### ISSUE TITLE
Lisans bilgisi ricası

### ISSUE THREAD

**Issue by hwpplayer1** [ubuntu-tr/Kabuk-ShellScript#10]
Merhaba, 

Ubuntu ve projelerine dikkatimi tekrar vermeye başladım. Bu proje için teşekkür ederim. Umarım katkı sağlayabilirim. Kendi lisansımı getirip getiremeyeceğimi sormak istedim.

Teşekkürler, iyi bayramlar

**Comment by siberoloji** [comment]
Merhaba,
Tabii ki. Uygundur.
Daha güzel projeler yapmanız ümidiyle.
İyi bayramlar.

**Comment by hwpplayer1** [comment]
Teşekkürler, görüşmek üzere 1-2 hafta içinde basit bir script hazırlamaya çalışırım. Amaç işimi görsün ve yeni başlayanlar da heveslensin benim gibi. Aklıma gelen wi-fi çalışmadığında `sudo service network-manager restart` gibi veya update upgrade dist-upgrade gibi komutları derlemek. Belki kurulabilecek snap olmayan standard paketleri de ayrıca düşünebilirim. Ben şahsen GNU Emacs'e odaklandığım için onun için bir komut ekleyebilirim. Tarayıcıma issue bağlantısını ekledim.
